### ISSUE TITLE
error: initializer element is not constant

### ISSUE THREAD

**Issue by andrislapins** [edi-riga/MansOS#5]
Could not define a variable with arithmetic value assignment - example, int bar = 2 * foo.
Compilation requires it to be a simple value - example, int bar = 400

**Comment by jjanis** [comment]
Ths provided source code is not sufficient, but I am assuming that foo is an int not #define.

Citing the top google search with your error statement: https://stackoverflow.com/questions/3025050/error-initializer-element-is-not-constant-when-trying-to-initialize-variable-w

> In C language, objects with static storage duration have to be initialized with constant expressions, or with aggregate initializers containing constant expressions.

This is not C++ and it is the expected behaviour is C.
